version = 1

[[annotations]]
path = ["docs/source/_static/img/*.jpg", "docs/source/_static/img/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "All rights reserved"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = ["docs/source/**/*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "German Aerospace Center (DLR), Helmholtz-Zentrum Dresden-Rossendorf, Forschungszentrum Jülich"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "German Aerospace Center (DLR), Helmholtz-Zentrum Dresden-Rossendorf, Forschungszentrum Jülich"
SPDX-License-Identifier = "CC0-1.0"
